name: Test

on:
  pull_request:
    branches: dev
  push:
    branches: fix_arrays

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pacman -Syu --noconfirm docker docker-compose python sudo

      - name: build test image
        run: docker build . -t prosody

      - name: run tests
        run: cd ./tests/ && ./test.bash
