name: Test

on:
  pull_request:
    branches: dev
  push:
    branches: dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: install python3-venv
        run: sudo apt-get install python3-venv

      - name: build test image
        run: docker build . -t prosody

      - name: run tests
        run: cd ./tests/ && ./test.bash
